name: golangci-lint
on:
  push:
    branches:
      - master
      - main
  pull_request:
jobs:
  lint_and_test:
    name: lint
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        go: ['1.14.x', '1.15.x', '1.16.x']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v2.1.3
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
      - name: test
        run: go test -race -v ./...
